set_setpoints:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: gen24_battery_control
    control_mode:
      selector:
        select:
          translation_key: control_mode
          options:
            - auto
            - limit_charge
            - limit_discharge
            - limit_both
    discharge_limit:
      selector:
        number:
          min: -100
          max: 100
          step: 0.01
          unit_of_measurement: "%"
          mode: box
    charge_limit:
      selector:
        number:
          min: -100
          max: 100
          step: 0.01
          unit_of_measurement: "%"
          mode: box
    min_reserve:
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: box
    revert_timeout:
      selector:
        number:
          min: 0
          max: 3600
          step: 1
          unit_of_measurement: s
          mode: box
    grid_charging:
      selector:
        boolean:
